name: finance

services:
  swagger:
    build: swagger-ui
    image: swagger-finance:1.0.0
    ports:
      - 81:8080
    networks:
      - mynetwork
  pg_db:
    build: postgresql
    image: postgresql-finance:1.0.0
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: 123
    networks:
      - mynetwork
  pgadmin:
    build: pgadmin
    image: pgadmin-finance:1.0.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: finance
    ports:
      - 82:80
    networks:
      - mynetwork
  account-service:
    build: service-account
    image: account-service:1.0.2
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db:5432/account_service
      SPRING_DATASOURCE_USERNAME: FIN_account_service_app
      SPRING_DATASOURCE_PASSWORD: account
    networks:
      - mynetwork
    depends_on:
      - pg_db	
  audit-service:
    build: service-audit
    image: audit-service:1.0.2
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db:5432/audit_service
      SPRING_DATASOURCE_USERNAME: FIN_audit_service_app
      SPRING_DATASOURCE_PASSWORD: audit
    networks:
      - mynetwork
    depends_on:
      - pg_db
  classifier-service:
    build: service-classifier
    image: classifier-service:1.0.2
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db:5432/classifier_service
      SPRING_DATASOURCE_USERNAME: FIN_classifier_service_app
      SPRING_DATASOURCE_PASSWORD: classifier
    networks:
      - mynetwork
    depends_on:
      - pg_db
  user-service:
    build: service-user
    image: user-service:1.0.2
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db:5432/user_service
      SPRING_DATASOURCE_USERNAME: FIN_user_service_app
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - mynetwork
    depends_on:
      - pg_db
  proxy:
    build: proxy
    image: proxy-finance:1.0.0
    ports:
      - 80:80
    networks:
      - mynetwork	  

networks:
  mynetwork: