server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/account_service
    username: FIN_account_service_app
    password: account
  cloud:
    openfeign:
      client:
        config:
          userClientFeign:
            url: http://user-service:8080/cabinet/me
          auditClientFeign:
            url: http://audit-service:8080/audit
          classifierClientFeign:
            url: http://classifier-service:8080/classifier