server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service
    username: FIN_account_service_app
    password: account

  cloud:
    openfeign:
      client:
        config:
          userClientFeign:
            url: http://localhost:8080/cabinet/me
          auditClientFeign:
            url: http://localhost:8081/audit
          classifierClientFeign:
            url: http://localhost:8082/classifier