server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service
    username: FIN_account_service_app
    password: account

urlUserClientFeign: http://localhost:8080/cabinet/me
urlAuditClientFeign: http://localhost:8080/audit
urlClassifierClientFeign: http://localhost:8080/classifier