server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg_db:5432/account_service
    username: FIN_account_service_app
    password: account


urlUserClientFeign: http://user-service:8080/cabinet/me
urlAuditClientFeign: http://audit-service:8080/audit
urlClassifierClientFeign: http://classifier-service:8080/classifier