server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service
    username: FIN_audit_service_app
    password: audit

  cloud:
    openfeign:
      client:
        config:
          userClientFeign:
            url: http://localhost:8080/cabinet/me
          auditClientFeign:
            url: http://localhost:8081/audit
