server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/audit_service
    username: FIN_audit_service_app
    password: audit

  cloud:
    openfeign:
      client:
        config:
          userClientFeign:
            url: http://user-service:8080
          auditClientFeign:
            url: http://audit-service:8080/audit
