server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service
    username: FIN_audit_service_app
    password: audit

app:
  jwt:
    secret: 34c1bc41c744158bdce2b21894ba0422ce24d474ecdac088138f4bde72804918
    issuer: FinanceApp


