server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/audit_service
    username: FIN_audit_service_app
    password: audit

urlUserClientFeign: http://user-service:8080
urlAuditClientFeign: http://audit-service:8080/audit
