server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service
    username: FIN_audit_service_app
    password: audit

urlUserClientFeign: http://localhost:8080
urlAuditClientFeign: http://localhost:8080/audit
