server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: FIN_user_service_app
    password: qwe123
  mail:
    host: smtp.mail.ru
    port: 587
    username: annatsurko2003@mail.ru
    password: 1

message:
  server: localhost:${server.port}
  username: ${spring.mail.username}
  subject: FinanceApp



