spring:
  main:
    allow-bean-definition-overriding: true

app:
  jwt:
    secret: 34c1bc41c744158bdce2b21894ba0422ce24d474ecdac088138f4bde72804918
    issuer: FinanceApp

verify-code:
  length: 25
  letters: true
  numbers: true
