project:
  version: v1

server:
  port: 8080
  address: user-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg_db:5432/user_service
    username: FIN_user_service_app
    password: user

  mail:
    host: smtp.mail.ru
    port: 587
    username: annatsurko2003@mail.ru
    password: nggrtU3WtsD6yjxHcre6

urlAuditClientFeign: http://audit-service:8080/audit

message:
  server: ${server.address}:${server.port}
  username: ${spring.mail.username}
  subject: FinanceApp
  version: ${project.version}