project:
  version: v1

server:
  port: 8080
  address: localhost

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: FIN_user_service_app
    password: qwe123
  mail:
    host: smtp.mail.ru
    port: 587
    username: annatsurko2003@mail.ru
    password: 1

message:
  server: ${server.address}:${server.port}
  username: ${spring.mail.username}
  subject: FinanceApp
  version: ${project.version}

app:
  jwt:
    secret: 1
    issuer: FinanceApp



