server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg_db:5432/classifier_service
    username: FIN_classifier_service_app
    password: classifier


urlUserClientFeign: http://user-service:8080/cabinet/me
urlAuditClientFeign: http://audit-service:8080/audit