server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classifier_service
    username: FIN_classifier_service_app
    password: classifier

urlUserClientFeign: http://localhost:8080/cabinet/me
urlAuditClientFeign: http://localhost:8080/audit
