server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/classifier_service
    username: FIN_classifier_service_app
    password: classifier

  cloud:
    openfeign:
      client:
        config:
          userClientFeign:
            url: http://user-service:8080/cabinet/me
          auditClientFeign:
            url: http://audit-service:8080/audit
