server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classifier_service
    username: FIN_classifier_service_app
    password: classifier

  cloud:
    openfeign:
      client:
        config:
          userClientFeign:
            url: http://localhost:8080/cabinet/me
          auditClientFeign:
            url: http://localhost:8081/audit
